package models

data class CanonicalScenario(val id: Int, val nameEngU: String) {
  override fun toString() = nameEngU
  val baiEntryID = 83+id*2
  val bsiEntryID = baiEntryID + 1
  val terrainID = 365 + id

  val textSBase: Map<Language, Int> = mapOf(
    Language.JP to 8641 + id,
    Language.ENG_U to 10754 + 1803 * 0 + id,
    Language.ENG_E to 10754 + 1803 * 1 + id,
    Language.GER to 10754 + 1803 * 2 + id,
    Language.FRA_E to 10754 + 1803 * 3 + id,
    Language.FRA_U to 10754 + 1803 * 4 + id,
    Language.ESP_E to 10754 + 1803 * 5 + id,
    Language.ESP_U to 10754 + 1803 * 6 + id,
    Language.ITA to 10754 + 1803 * 7 + id,
    Language.KOR to 10754 + 1803 * 8 + id,
    Language.TWN to 10754 + 1803 * 9 + id,
    Language.CHN to 10754 + 1803 * 10 + id,
  )

  val textVBase: Map<Language, Int> = mapOf(
    Language.JP to 8539 + id,
    Language.ENG_U to 10652 + id,
    Language.ENG_E to 12455 + id,
    Language.GER to 12455 + 1803 * 1 + id,
    Language.FRA_E to 12455 + 1803 * 2 + id,
    Language.FRA_U to 12455 + 1803 * 3 + id,
    Language.ESP_E to 12455 + 1803 * 4 + id,
    Language.ESP_U to 12455 + 1803 * 5 + id,
    Language.ITA to 12455 + 1803 * 6 + id,
    Language.KOR to 12455 + 1803 * 7 + id,
    Language.TWN to 12455 + 1803 * 8 + id,
    Language.CHN to 12455 + 1803 * 9 + id,
  )
  val textBBase: Map<Language, Int> = mapOf(
    Language.JP to 8743 + id,
    Language.ENG_U to 10856 + 1803 * 0 + id,
    Language.ENG_E to 10856 + 1803 * 1 + id,
    Language.GER to 10856 + 1803 * 2 + id,
    Language.FRA_E to 10856 + 1803 * 3 + id,
    Language.FRA_U to 10856 + 1803 * 4 + id,
    Language.ESP_E to 10856 + 1803 * 5 + id,
    Language.ESP_U to 10856 + 1803 * 6 + id,
    Language.ITA to 10856 + 1803 * 7 + id,
    Language.KOR to 10856 + 1803 * 8 + id,
    Language.TWN to 10856 + 1803 * 9 + id,
    Language.CHN to 10856 + 1803 * 10 + id,
  )
}

private var ascScenarioID: Int = 0
private fun asc(title: String) = CanonicalScenario(ascScenarioID++, title)

val canonicalScenarios = arrayOf(
  asc("A Skirmish at Dawn"),
  asc("Rivalry of the Houses"),
  asc("Red Canyon Dominance"),
  asc("The Magdred Ambush"),
  asc("Assault at the Rite of Rebirth"),
  asc("The Gautier Inheritance"),
  asc("The Underground Chamber"),
  asc("Battle of the Eagle and Lion"),
  asc("The Remire Calamity"),
  asc("Salvation at the Chapel"),
  asc("The Sealed Forest Snare"),
  asc("Conflict in the Holy Tomb"),
  asc("The Battle of Garreg Mach"),
  asc("Hunting by Daybreak"),
  asc("Protecting Garreg Mach"),
  asc("Ambush at Ailell"),
  asc("The Great PlatformLogger.Bridge Coup"),
  asc("To War at Gronder"),
  asc("To War at Gronder"),
  asc("Taking Fort Merceus"),
  asc("Taking Fort Merceus"),
  asc("Reclaiming the Capital"),
  asc("The Enbarr Infiltration"),
  asc("Saving Derdriu"),
  asc("Confrontation at the Palace"),
  asc("Taking Fort Merceus"),
  asc("Stand Strong at Shambhala"),
  asc("Assault on Enbarr"),
  asc("The Final Battle"),
  asc("For the Freedom of Fódlan"),
  asc("Clash at the Imperial Capital"),
  asc("The Battle of Garreg Mach"),
  asc("The Great Bridge Coup"),
  asc("Capturing Derdriu"),
  asc("Protecting Garreg Mach"),
  asc("The Siege of Arianrhod"),
  asc("Combat at Tailtean Plains"),
  asc("The Fight for Fhirdiad"),
  asc("Eternal Guardian"),
  asc("The Silver Maiden"),
  asc("Insurmountable"),
  asc("The Sleeping Sand Legend"),
  asc("Tales of the Red Canyon"),
  asc("War for the Weak"),
  asc("True Chivalry"),
  asc("Falling Short of Heaven"),
  asc("The Forgotten"),
  asc("The Face Beneath"),
  asc("Weathervanes of Fódlan"),
  asc("Rumored Nuptials"),
  asc("Darkness Beneath the Earth"),
  asc("Retribution"),
  asc("Legend of the Lake"),
  asc("Foreign Land and Sky"),
  asc("Land of the Golden Deer"),
  asc("Death Toll"),
  asc("Forgotten Hero"),
  asc("Dividing the World"),
  asc("An Ocean View"),
  asc("Oil and Water"),
  asc("Sword and Shield of Seiros"),
  asc("Battle in the Outskirts"),
  asc("Battle in the Mountains"),
  asc("Battle in the Empire"),
  asc("Battle in the Kingdom"),
  asc("Battle in the Desert"),
  asc("Battle at Magdred Way"),
  asc("Battle at the Border"),
  asc("Battle on the Plateau"),
  asc("Monsters on the Road"),
  asc("Monsters in the Mountains"),
  asc("Monsters in the Desert"),
  asc("Battle at Gronder Field"),
  asc("Monsters at Gronder Field"),
  asc("Battle in the Ruins"),
  asc("Monsters in the Ruins"),
  asc("Monsters in the Red Canyon"),
  asc("Bandits on the Rhodos Coast"),
  asc("Western Church Suppression"),
  asc("Battle in Ailell"),
  asc("Monsters on the Plains"),
  asc("Battle at Lake Teutates"),
  asc("Battle in the Forest"),
  asc("Battle in the Plains"),
  asc("Battle at the Sealed Forest"),
  asc("Battle at Conand Tower"),
  asc("A Skirmish in Abyss"),
  asc("Ambush in the Arena"),
  asc("Search for the Chalice"),
  asc("A Harrowing Escape"),
  asc("Besieged in the Chapel Ruins"),
  asc("The Rite of Rising"),
  asc("A Beast in the Cathedral"),
  asc("Black Market Scheme"),
  asc("A Cursed Relic"),
  asc("<<BLANK>>"),
  asc("<<BLANK>>"),
  asc("The Secret Merchant"),
  asc("<<BLANK>>"),
  asc("<<BLANK>>"),
)
